//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTD_02.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_Hidebars {
            get {
                return ((string)(this["usr_Hidebars"]));
            }
            set {
                this["usr_Hidebars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_Outlinebars {
            get {
                return ((string)(this["usr_Outlinebars"]));
            }
            set {
                this["usr_Outlinebars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_Outlinepart {
            get {
                return ((string)(this["usr_Outlinepart"]));
            }
            set {
                this["usr_Outlinepart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ggggg")]
        public string usr_Hidepart {
            get {
                return ((string)(this["usr_Hidepart"]));
            }
            set {
                this["usr_Hidepart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_Showbars {
            get {
                return ((string)(this["usr_Showbars"]));
            }
            set {
                this["usr_Showbars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_Showpart {
            get {
                return ((string)(this["usr_Showpart"]));
            }
            set {
                this["usr_Showpart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_BmLong {
            get {
                return ((string)(this["usr_BmLong"]));
            }
            set {
                this["usr_BmLong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_BmLongCust {
            get {
                return ((string)(this["usr_BmLongCust"]));
            }
            set {
                this["usr_BmLongCust"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_BmSimple {
            get {
                return ((string)(this["usr_BmSimple"]));
            }
            set {
                this["usr_BmSimple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_Cloud {
            get {
                return ((string)(this["usr_Cloud"]));
            }
            set {
                this["usr_Cloud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FcrNote {
            get {
                return ((string)(this["usr_FcrNote"]));
            }
            set {
                this["usr_FcrNote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FilterAdded {
            get {
                return ((string)(this["usr_FilterAdded"]));
            }
            set {
                this["usr_FilterAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FilterAddedBars {
            get {
                return ((string)(this["usr_FilterAddedBars"]));
            }
            set {
                this["usr_FilterAddedBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FilterAddedLinks {
            get {
                return ((string)(this["usr_FilterAddedLinks"]));
            }
            set {
                this["usr_FilterAddedLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FilterDeleted {
            get {
                return ((string)(this["usr_FilterDeleted"]));
            }
            set {
                this["usr_FilterDeleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FilterDeletedBars {
            get {
                return ((string)(this["usr_FilterDeletedBars"]));
            }
            set {
                this["usr_FilterDeletedBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string usr_FilterDeletedLinks {
            get {
                return ((string)(this["usr_FilterDeletedLinks"]));
            }
            set {
                this["usr_FilterDeletedLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double usr_BarMarkYOffset {
            get {
                return ((double)(this["usr_BarMarkYOffset"]));
            }
            set {
                this["usr_BarMarkYOffset"] = value;
            }
        }
    }
}
